# Generated by Django 3.2.14 on 2022-07-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
