# Generated by Django 3.2.14 on 2022-07-14 13:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
